# CircleCI 2.0 configuration file
version: 2
jobs:
  build-job:
    docker:
      - image: circleci/node:8.10.0-browsers

    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run build
      - run: yarn install && yarn build

  deploy-job:
    docker:
      - image: circleci/node:8.10.0-browsers
    steps:
      - checkout
      - run:
          name: Deploy to S3
          environment:
            NODE_ENV: production
            APP_URL: https://healfit.co.uk
            API_URL: https://api.healfit.co.uk
            BUGSNAG_API_KEY: 3ed18fabf2445b22b785f539282a439a
            GA_API_KEY: UA-132673441-1
            CLOUDINARY_PRESET: wyifndmn
            MIX_PANEL_TOKEN: 1c593bee1118657e7b0ad44c61996399
          command: |
            sudo apt-get install python-dev python-pip
            sudo pip install awscli
            yarn install --production=false
            yarn build
            aws s3 sync ~/project/dist s3://healfit.co.uk --delete
            aws cloudfront create-invalidation --distribution-id E2H4X46OP5N91X --paths /*
            aws cloudfront create-invalidation --distribution-id EEW1QT8BI9JTU --paths /*
workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only: master
